/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Search Agent API
 * OpenAPI spec version: 0.1.0
 */
import type { MessageId } from './messageId';

export interface Message {
  type: string;
  content: string;
  id?: MessageId;
}
