/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Search Agent API
 * OpenAPI spec version: 0.1.0
 */
import type { SearchRequestThreadId } from './searchRequestThreadId';
import type { SearchRequestMessageId } from './searchRequestMessageId';

export interface SearchRequest {
  query: string;
  thread_id?: SearchRequestThreadId;
  message_id?: SearchRequestMessageId;
}
