/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Search Agent API
 * OpenAPI spec version: 0.1.0
 */
import type { Message } from './message';

export interface ThreadResponse {
  messages: Message[];
}
