/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Search Agent API
 * OpenAPI spec version: 0.1.0
 */

/**
 * Thread metadata model.
 */
export interface ThreadMetadata {
  thread_id: string;
  title: string;
  created_at?: string;
  updated_at?: string;
}
